//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaviOnlineOrdering2018
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HAVIEntities : DbContext
    {
        public HAVIEntities()
            : base("name=HAVIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Cart> tbl_Cart { get; set; }
        public DbSet<tbl_Transaction> tbl_Transaction { get; set; }
        public DbSet<tbl_items_sl> tbl_items_sl { get; set; }
        public DbSet<tbl_items> tbl_items { get; set; }
        public DbSet<tbl_item_mstr> tbl_item_mstr { get; set; }
        public DbSet<tbl_Category> tbl_Category { get; set; }
        public DbSet<tbl_store> tbl_store { get; set; }
        public DbSet<tbl_Customer> tbl_Customer { get; set; }
        public DbSet<vw_AllowedItemsOnStore> vw_AllowedItemsOnStore { get; set; }
        public DbSet<tbl_SpecialItemStore> tbl_SpecialItemStore { get; set; }
    }
}
