//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaviOnlineOrdering2018
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data;
    using System.Linq;
    using HaviOnlineOrdering2018.BLL;

    public partial class tbl_Cart
    {
        public string cart_id { get; set; }
        public string wrin { get; set; }
        public Nullable<decimal> price { get; set; }
        public int qty { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> delivered_qty { get; set; }
        public string downloaded { get; set; }
        public Nullable<System.DateTime> datedownloaded { get; set; }
        public string TextFileName { get; set; }

        private tbl_item_mstr mItem = null;
        public tbl_item_mstr iteminfo
        {
            get
            {
                if (mItem == null)
                {
                    mItem = new tbl_item_mstr();
                    using (HAVIEntities dbContext = new HAVIEntities())
                    {
                        mItem = dbContext.tbl_item_mstr.Where(x => x.Wrin.Trim() == wrin).FirstOrDefault();
                    }
                }

                return mItem;
            }
        }

        public decimal totalprice
        {
            get
            {
                decimal res = 0;

                res = new UtilityBLL(null).ConvertToDecimal(price) * new UtilityBLL(null).ConvertToDecimal(qty);

                return res;
            }
        }
    }
}
