//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaviOnlineOrdering2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Category
    {
        public int category_id { get; set; }
        public string category_name { get; set; }
        public string category_code { get; set; }
        public int owner_id { get; set; }
    }
}
