//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaviOnlineOrdering2018
{
    using System;
    using System.Collections.Generic;

    public partial class tbl_Transaction
    {
        private bool mSpecialHasValue;
        public bool SpecialHasValue { get { return mSpecialHasValue; } set { mSpecialHasValue = value; } }

        private int mOrder_no;
        public int Order_no { get { return mOrder_no; } set { mOrder_no = value; } }
        public int Custid { get; set; }
        public string Store_no { get; set; }
        protected string mrefpo;
        public string refpo { get { return this.mrefpo; } set { this.mrefpo = (value == null ? value : value.Trim()); } }
        protected string mTrans_Type;

        private bool mSpecial;
        public bool Special
        {
            get
            {
                if (!SpecialHasValue)
                {
                    mSpecial = Trans_type == "S";
                    SpecialHasValue = true;
                }
                return mSpecial;
            }
            set
            {
                mSpecial = value;
            }
        }
        public string Trans_type { get { return this.mTrans_Type; } set { this.mTrans_Type = value; } }

        public System.DateTime Trans_date { get; set; }

        public System.DateTime Delivery_date { get; set; }
        protected string mDel_date = string.Empty;
        public string Del_date { get { if (mDel_date == null || mDel_date == string.Empty) { return Delivery_date.ToShortDateString(); } return mDel_date; } set { mDel_date = value; } }
        public System.DateTime SpecialDelDate { get; set; }
        public string Cart_id { get; set; }
        public decimal Total { get; set; }
        public string Trans_status { get; set; }

        public string Status
        {
            get
            {
                if (Trans_status == "N" || Trans_status.ToUpper() == "NEW")
                {
                    return "NEW";
                }
                else
                {
                    return "PROCESSED";
                }
            }
        }
        public int owner_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string careof { get; set; }
        public string so_time { get; set; }
        public string cc_stat { get; set; }
        public string r_stat { get; set; }
        public string freight_mode { get; set; }
        public Nullable<int> WebUtilityID { get; set; }
        public Nullable<System.DateTime> DateUnprocess { get; set; }





    }
}
