//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaviOnlineOrdering2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_items_sl
    {
        public string store_no { get; set; }
        public string wrin { get; set; }
        public Nullable<int> Modified_by { get; set; }
    }
}
