//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaviOnlineOrdering2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_item_mstr
    {
        public string Wrin { get; set; }
        public string Item_desc { get; set; }
        public string Entity_code { get; set; }
        public string split_code { get; set; }
        public string abc_class { get; set; }
        public string uom { get; set; }
        public string item_cat { get; set; }
        public string item_type { get; set; }
        public string item_source { get; set; }
        public string shelf_life { get; set; }
        public Nullable<int> Min_Stock_level { get; set; }
        public string item_stat { get; set; }
        public Nullable<int> pia_no { get; set; }
        public Nullable<int> safety_level { get; set; }
        public string gl_acct_code { get; set; }
        public string item_sub_cat { get; set; }
        public string english_desc { get; set; }
        public string english_uom { get; set; }
        public string ret_wrin { get; set; }
        public string ret_desc { get; set; }
        public Nullable<int> ret_case { get; set; }
        public string charge_service { get; set; }
        public Nullable<decimal> ret_deposit { get; set; }
        public string vat_ind { get; set; }
        public Nullable<decimal> case_del_unit { get; set; }
        public string dep_wrin { get; set; }
        public string charge_to { get; set; }
        public Nullable<System.DateTime> Effect_date { get; set; }
        public string msi_item { get; set; }
        public string msm_cat { get; set; }
        public string msm_subcat { get; set; }
        public string Pur_UOM { get; set; }
        public string dep_case { get; set; }
        public string hs_code { get; set; }
        public string whse_code { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
        public string case_pk { get; set; }
        public Nullable<decimal> case_cube { get; set; }
        public Nullable<decimal> case_wt { get; set; }
        public Nullable<decimal> product_cost { get; set; }
        public Nullable<decimal> whse_cost { get; set; }
        public Nullable<decimal> std_price { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
