//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaviOnlineOrdering2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        public int custid { get; set; }
        public string login_email { get; set; }
        public string password { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string phoneno { get; set; }
        public string faxno { get; set; }
        public string address { get; set; }
        public Nullable<int> owner_id { get; set; }
        public string access_type { get; set; }
        public string store_no { get; set; }
        public string cust_rights { get; set; }
        public string cstatus { get; set; }
        public Nullable<System.DateTime> dateopened { get; set; }
        public Nullable<int> lastaccess { get; set; }
        public Nullable<System.DateTime> dateaccess { get; set; }
        public string toggle_prc { get; set; }
        public string DwnldTime { get; set; }
        public string cust_rights2 { get; set; }
    }
}
