//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaviOnlineOrdering2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SpecialItemStore
    {
        public int SpecialItemStoreID { get; set; }
        public int category_id { get; set; }
        public string wrin { get; set; }
        public string StoreNo { get; set; }
        public int delday_hop { get; set; }
        public string orderday_exclusion_arr { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int IsActive { get; set; }
        public string ord_day { get; set; }
        public string override_hopcnt { get; set; }
    }
}
