//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaviOnlineOrdering2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_store
    {
        public int owner_id { get; set; }
        public string store_no { get; set; }
        public string store_name { get; set; }
        public string delday1 { get; set; }
        public string delday2 { get; set; }
        public string delday3 { get; set; }
        public string delday4 { get; set; }
        public string delday5 { get; set; }
        public string delday6 { get; set; }
        public string delday7 { get; set; }
        public string deltime1 { get; set; }
        public string deltime2 { get; set; }
        public string deltime3 { get; set; }
        public string deltime4 { get; set; }
        public string deltime5 { get; set; }
        public string deltime6 { get; set; }
        public string deltime7 { get; set; }
        public string toggle_prc { get; set; }
        public string bill_to { get; set; }
        public string ship_to { get; set; }
        public string cust_type { get; set; }
        public string corp_no { get; set; }
        public string area_code { get; set; }
        public string gl_acct_code { get; set; }
        public string charge_service { get; set; }
        public string status { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public Nullable<int> cia_no { get; set; }
        public string dwnldtime { get; set; }
        public string group_id { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string zcode { get; set; }
        public Nullable<int> WUtility_StoreCatID { get; set; }
        public Nullable<int> Wutility_UpdateBy { get; set; }
        public Nullable<System.DateTime> Wutility_UpdateDateTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
