//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaviOnlineOrdering2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_items
    {
        public int owner_id { get; set; }
        public int category_id { get; set; }
        public string wrin { get; set; }
        public string item_desc { get; set; }
        public string case_pk { get; set; }
        public Nullable<decimal> case_cu { get; set; }
        public Nullable<decimal> case_we { get; set; }
        public Nullable<decimal> std_price { get; set; }
        public Nullable<decimal> product_cost { get; set; }
        public Nullable<decimal> whse_cost { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> sup_price { get; set; }
        public string uom { get; set; }
        public Nullable<System.DateTime> as_of { get; set; }
        public Nullable<int> WUtility_ItemCatID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
