//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaviOnlineOrdering2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AllowedItemsOnStore
    {
        public Nullable<int> owner_id { get; set; }
        public string store_no { get; set; }
        public int category_id { get; set; }
        public string wrin { get; set; }
        public string item_desc { get; set; }
        public string case_pk { get; set; }
        public Nullable<decimal> case_cu { get; set; }
        public Nullable<decimal> case_we { get; set; }
        public string uom { get; set; }
        public Nullable<decimal> std_price { get; set; }
    }
}
